

```{r, include = FALSE}
# Libraries
library(here)
library(dplyr)
library(ids)
library(tidyr, include.only = "crossing")
library(lubridate, include.only = c("year", "month", "day"))
```

```{r, include=FALSE}
# mock data
# mrns
set.seed(1)
mrn <- ids::random_id(900, 4)

```

```{r, include=FALSE}
# Visit dates
dates <- data.frame(dates = seq(as.Date('2024-06-01'), as.Date('2024-09-30'), by = "day")) 
times <- c(paste0(9:17, ":00:00"), paste0(9:17, ":30:00"))

visit_date_time <- tidyr::crossing(dates, data.frame(times)) %>% 
  mutate(
    visit_date = as.POSIXct(paste0(dates, times))
  ) %>% select(visit_date)
```

```{r, include=FALSE}
# Physician and clinics
clincs_phys <- read.csv(here::here("data", "clinics_physicians.csv")) %>%
  mutate(id = c(1:68))

```

```{r, include=FALSE}
set.seed(1)
mock_data_rc <- visit_date_time %>% arrange(visit_date) %>%
  mutate(
    mrn = sample(mrn, nrow(.), replace = TRUE),
    id = sample(c(1:68), nrow(.), replace = TRUE)
  ) %>% left_join(., clincs_phys, by = "id") %>%
  select(-c(id)) %>%
  relocate(mrn, .before = "visit_date")
```

```{r, include=FALSE}
set.seed(12)

mock_data <- mock_data_rc %>% mutate(
  eligible = sample(c(0,1), nrow(.), replace = TRUE, prob = c(0.2, 0.8)),
  screened = case_when(
    eligible == 0 ~ 0,
    eligible == 1 ~ sample(c(0,1), nrow(.), replace = TRUE, prob = c(0.6, 0.4))
  ),
  # perc_completed = sample(c(sample(c(8:99), 659, replace = TRUE), rep(100, 1537)))
  num_completed = sample(c(sample(c(0:13), 659, replace = TRUE), rep(12, 1537))),
  perc_completed = (num_completed/12)*100 
)
```


```{r, include = FALSE}
mock_data <- mock_data %>% mutate(
  month = month(visit_date),
  month_name = month.abb[month],
  year = year(visit_date),
  month_year = paste(month_name, year, sep = " ")
) %>%
  group_by(month_year, clinic_name) %>%
  mutate(
  perc_screened_month_clinic = format(round((sum(screened)/sum(eligible))*100, digits = 2),nsmall=2),
  perc_items_month_clinic = format(round(mean(perc_completed), digits = 2),nsmall=2)
  ) %>%
  ungroup() %>%
  group_by(month_year, name_full_phys) %>%
  mutate(
  perc_screened_month_phys = format(round((sum(screened)/sum(eligible))*100, digits = 2),nsmall=2),
  perc_items_month_phys = format(round(mean(perc_completed), digits = 2),nsmall=2)
  ) %>%
  ungroup()
```

```{r, include = FALSE}
saveRDS(mock_data_rc, here::here("data", "mock_data_redcap_alerts.rds"))
saveRDS(mock_data, here::here("data", "mock_data.rds"))
```

